### ISSUE TITLE
Fresh install doesn't work?

### ISSUE THREAD

**Issue by jonmiranda** [wongcain/metronome-android#2]
Opened in Android Studio, Compiled and opened on my Nexus 6. Pressing play changes the icon to the stop symbol, but nothing else seems to occur.

**Comment by wongcain** [comment]
Hi.  I just did a fresh clone and ran it on my HTC One and it worked fine.  Perhaps your volume is turned down?  Note that I am playing the beat sounds just using AudioManager.playSoundEffect(int effectType, float volume), so the actual sounds you hear will vary from phone to phone.  It could easily be modified to reference packaged wave files for more cross-device consistency.

**Comment by jonmiranda** [comment]
Ah I see. I had my media volume turned up but my ring volume was silent.

Thanks!
Jon.
